name: Upload Hello World Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create Hello World file
      run: echo "Hello, world!" > hello_world.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-artifact
        path: hello_world.txt
